In [18]:
#Su dung numpy nhan ma tran M(R) . M(S)
import numpy as np

In [20]:
R = np.array([[0, 1, 0], 
     [0, 1, 0],
     [1, 0, 0],
     [1, 0, 1]])

In [22]:
S = np.array([[0, 0, 1, 0, 0],
     [0, 1, 0, 1, 0],
     [0, 0, 1, 0, 1]])

In [25]:
R.dot(S).astype(bool).astype(int)

array([[0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 1]])

In [32]:
M = np.array([
    [1, 1, 1, 0],
    [1, 1, 1, 0],
    [1, 1, 1, 0],
    [0, 0, 0, 1]
])

In [33]:
a = 1
for i in range(4):
    a = a and M[i, i] == 1
a

True

In [35]:
#Kiem tra tinh doi xung
M.T == M

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [36]:
(M.T == M).prod()

1

In [ ]:
#Kiem tra tinh phan xung
M.T & M  <= np.eye(4)

array([[ True, False, False,  True],
       [False,  True, False,  True],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [42]:
(M.T & M  <= np.eye(4)).prod()

0

In [45]:
#Kiem tra tinh chat bac cau
M.dot(M).astype(bool).astype(int)

array([[1, 1, 1, 0],
       [1, 1, 1, 0],
       [1, 1, 1, 0],
       [0, 0, 0, 1]])

In [46]:
M.dot(M).astype(bool).astype(int) <= M

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [47]:
(M.dot(M).astype(bool).astype(int) <= M).prod()

1