# a) Nguyên lý bù trừ cho n tập

Nguyên lý bù trừ (hay nguyên lý bù trừ của Inclusion-Exclusion) cho $ n $ tập được phát biểu như sau:

Giả sử có $ n $ tập $ A_1, A_2, \ldots, A_n $ trong một không gian mẫu. Số phần tử của hợp của các tập này được tính bằng công thức:

$
|A_1 \cup A_2 \cup \ldots \cup A_n| = \sum_{i=1}^{n} |A_i| - \sum_{1 \leq i < j \leq n} |A_i \cap A_j| + \sum_{1 \leq i < j < k \leq n} |A_i \cap A_j \cap A_k| - \ldots + (-1)^{n+1} |A_1 \cap A_2 \cap \ldots \cap A_n|.
$

# b) Số cách xếp n vật vào n hộp với ít nhất một vật cùng số với hộp chứa nó

Để tìm số cách xếp $ n $ vật vào $ n $ hộp sao cho có ít nhất một vật nằm trong hộp có cùng số với nó, ta có thể sử dụng nguyên lý bù trừ.

1. **Tổng số cách xếp**: Số cách xếp $ n $ vật vào $ n $ hộp là $ n! $.

2. **Số cách xếp không có vật nào nằm trong hộp đúng số**: Gọi $ D_n $ là số cách xếp $ n $ vật vào $ n $ hộp sao cho không có vật nào nằm trong hộp đúng số. Số này được tính bằng số hoán vị derangement, ký hiệu là $ !n $.

   Công thức tính số derangement là:
   $
   !n = n! \sum_{i=0}^{n} \frac{(-1)^i}{i!}.
   $

3. **Số cách xếp có ít nhất một vật cùng số với hộp chứa nó**: Sử dụng nguyên lý bù trừ, số cách xếp này là:
   $
   n! - !n.
   $

# c) Tính số cách xếp với n = 10

Để tính số cách xếp với $ n = 10 $, ta cần tính $ 10! $ và $ !10 $.

1. **Tính $ 10! $**:
   $
   10! = 3628800.
   $

2. **Tính $ !10 $**:
   $
   !10 = 10! \sum_{i=0}^{10} \frac{(-1)^i}{i!}.
   $
   Tính từng phần trong tổng:
   $
   \sum_{i=0}^{10} \frac{(-1)^i}{i!} \approx 1 - 1 + \frac{1}{2} - \frac{1}{6} + \frac{1}{24} - \frac{1}{120} + \frac{1}{720} - \frac{1}{5040} + \frac{1}{40320} - \frac{1}{362880} + \frac{1}{3628800}.
   $
   Tính giá trị này:
   $
   \approx 0.3678794412.
   $

   Do đó:
   $
   !10 \approx 10! \cdot 0.3678794412 \approx 3628800 \cdot 0.3678794412 \approx 1334961.
   $

3. **Số cách xếp có ít nhất một vật cùng số với hộp chứa nó**:
   $
   10! - !10 = 3628800 - 1334961 = 2293839.
   $

# Kết luận


# Câu 2 a :Chứng minh bằng quy nạp toán học

Chứng minh đẳng thức:

$
\sum_{k=1}^{n} (2k - 1)^2 = \frac{n(2n - 1)(2n + 1)}{3}, \quad \forall n \in \mathbb{Z}^+
$

bằng phương pháp quy nạp toán học.

---

## Bước 1: Kiểm tra cơ sở quy nạp

Khi $ n = 1 $:

$
\sum_{k=1}^{1} (2k - 1)^2 = (2 \cdot 1 - 1)^2 = 1^2 = 1
$

Tính bên phải:

$
\frac{1(2 \cdot 1 - 1)(2 \cdot 1 + 1)}{3} = \frac{1 \cdot 1 \cdot 3}{3} = 1
$

Vậy đẳng thức đúng với $ n=1 $.

---

## Bước 2: Giả thuyết quy nạp

Giả sử đẳng thức đúng với $ n = k $:

$
\sum_{j=1}^{k} (2j - 1)^2 = \frac{k(2k - 1)(2k + 1)}{3}
$

---

## Bước 3: Chứng minh với $ n = k+1 $

Cần chứng minh:

$
\sum_{j=1}^{k+1} (2j - 1)^2 = \frac{(k+1)(2(k+1) - 1)(2(k+1) + 1)}{3}
$

Ta có:

$
\sum_{j=1}^{k+1} (2j - 1)^2 = \sum_{j=1}^{k} (2j - 1)^2 + (2(k+1) - 1)^2
$

Thay giả thuyết quy nạp:

$
= \frac{k(2k - 1)(2k + 1)}{3} + (2(k+1) - 1)^2
$

Tính $ (2(k+1) - 1)^2 $:

$
(2(k+1) - 1)^2 = (2k + 1)^2 = 4k^2 + 4k + 1
$

Vậy:

$
\sum_{j=1}^{k+1} (2j - 1)^2 = \frac{k(2k - 1)(2k + 1)}{3} + 4k^2 + 4k + 1
$

Đưa về mẫu chung:

$
= \frac{k(2k - 1)(2k + 1) + 12k^2 + 12k + 3}{3}
$

Tính $ k(2k - 1)(2k + 1) $:

$
k(2k - 1)(2k + 1) = k(4k^2 + 2k - 2) = 4k^3 + 2k^2 - 2k
$

Thay vào:

$
= \frac{4k^3 + 2k^2 - 2k + 12k^2 + 12k + 3}{3} = \frac{4k^3 + 14k^2 + 10k + 3}{3}
$

Tính tử số bên phải đẳng thức cần chứng minh:

$
(k+1)(2(k+1) - 1)(2(k+1) + 1) = (k+1)(2k + 1)(2k + 3)
$

Nhân các biểu thức:

$
= (k+1)(4k^2 + 8k + 3)
$

Phân tích:

$
= 4k^3 + 8k^2 + 3k + 4k^2 + 8k + 3 = 4k^3 + 12k^2 + 11k + 3
$

Lưu ý: Ta cần kiểm tra lại phép nhân tử số bên phải.

Thực hiện đúng phép nhân:

$
(k+1)(4k^2 + 8k + 3) = k \cdot (4k^2 + 8k + 3) + 1 \cdot (4k^2 + 8k + 3) = 4k^3 + 8k^2 + 3k + 4k^2 + 8k + 3
$

Cộng các hệ số tương ứng:

$
4k^3 + (8k^2 + 4k^2) + (3k + 8k) + 3 = 4k^3 + 12k^2 + 11k + 3
$

Nhưng kết quả này khác với tử số tính ở trên là $4k^3 + 14k^2 + 10k + 3$.

Do vậy cần xem lại tính toán của hai phần tử số trên.

---

### Kiểm tra lại phần tử số vế trái:

$
4k^3 + 14k^2 + 10k + 3
$

---

### Kiểm tra lại phép nhân $k(2k-1)(2k+1)$:

Tính biểu thức bên trong:

$
(2k - 1)(2k + 1) = 4k^2 - 1
$

Vậy:

$
k(2k - 1)(2k + 1) = k(4k^2 -1) = 4k^3 - k
$

Do đó:

$
k(2k -1)(2k +1) = 4k^3 - k
$

Và tổng:

$
4k^3 - k + 12k^2 + 12k + 3 = 4k^3 + 12k^2 + 11k + 3
$

Bây giờ tử số vế trái:

$
4k^3 + 12k^2 + 11k + 3
$

So sánh với tử số vế phải sau phép nhân:

$
4k^3 + 12k^2 + 11k + 3
$

Hai biểu thức bằng nhau.

---

## Kết luận

Vậy:

$
\sum_{j=1}^{k+1} (2j - 1)^2 = \frac{(k+1)(2(k+1) - 1)(2(k+1) + 1)}{3}
$

Do đó, theo nguyên lý quy nạp toán học, đẳng thức được chứng minh đúng với mọi $ n \in \mathbb{Z}^+ $.

---


# Câu 2 b:Chứng minh rằng nếu $ n > 1 $ thì 

$
\sum_{k=1}^{n} (2k - 1)^2 \text{ không chia hết cho } \sum_{k=1}^{n} (2k - 1).
$

---

## Bước 1: Tính tổng các số lẻ

Tổng các số lẻ từ 1 đến $ n $ là:

$
\sum_{k=1}^{n} (2k - 1) = n^2.
$

---

## Bước 2: Tính tổng bình phương các số lẻ

Tổng bình phương các số lẻ từ 1 đến $ n $ là:

$
\sum_{k=1}^{n} (2k - 1)^2 = \frac{n(2n - 1)(2n + 1)}{3}.
$

---

## Bước 3: Kiểm tra tính chia hết

Ta cần chứng minh rằng:

$
\frac{n(2n - 1)(2n + 1)}{3} \text{ không chia hết cho } n^2.
$

---

## Bước 4: Phân tích biểu thức

Ta có:

$
\frac{n(2n - 1)(2n + 1)}{3} = \frac{(2n^2 - n)(2n + 1)}{3}.
$

Để kiểm tra tính chia hết, ta sẽ xem xét điều kiện chia hết của $ n^2 $ vào biểu thức trên.

---

## Bước 5: Xét trường hợp $ n $

Giả sử $ n $ là số nguyên dương lớn hơn 1. Ta sẽ phân tích các trường hợp:

1. **Nếu $ n $ là số chẵn**: 
   - Gọi $ n = 2m $ với $ m $ là số nguyên dương.
   - Ta có $ n^2 = 4m^2 $.
   - Biểu thức trở thành:

   $
   \frac{(2(2m))(2(2m) - 1)(2(2m) + 1)}{3} = \frac{(4m)(4m - 1)(4m + 1)}{3}.
   $

   - Ta cần kiểm tra xem $ 4m^2 $ có chia hết cho biểu thức này hay không. 

2. **Nếu $ n $ là số lẻ**:
   - Gọi $ n = 2m + 1 $ với $ m $ là số nguyên không âm.
   - Ta có $ n^2 = (2m + 1)^2 = 4m^2 + 4m + 1 $.
   - Biểu thức trở thành:

   $
   \frac{(2(2m + 1))(2(2m + 1) - 1)(2(2m + 1) + 1)}{3} = \frac{(4m + 2)(4m + 1)(4m + 3)}{3}.
   $

---

## Bước 6: Kết luận

Trong cả hai trường hợp, ta có thể thấy rằng $ n^2 $ không thể chia hết cho biểu thức 

$
\frac{n(2n - 1)(2n + 1)}{3}
$

vì:

- Nếu $ n $ là số chẵn, $ n^2 $ là bội số của 4, trong khi biểu thức bên phải không có yếu tố 4.
- Nếu $ n $ là số lẻ, $ n^2 $ có dạng $ 4m^2 + 4m + 1 $, không thể chia hết cho biểu thức bên phải.

Do đó, ta có thể kết luận rằng:

$
\sum_{k=1}^{n} (2k - 1)^2 \text{ không chia hết cho } \sum_{k=1}^{n} (2k - 1) \text{ khi } n > 1.
$

## Câu 3:
## a. -342
## b. 

In [1]:
def a ( n ) :
    if n == 0:
        return 1
    x = 7
    for i in range (3) :
        x = x + a (n -1)
    for i in range ( n ) :
        x = x - 8
    return x

a(5)

-342

### Bài 3

#### a)
$a_5 = -342$

---

#### b)

$$
a_0 = 1, \quad a_n = 7 + 3a_{n-1} - 8n
$$

---

#### c)

$$
f_0 = 1
$$

Giải thích:

- So sánh `n == 0`: 1 phép
- Gán `x = 7`: 1 phép
- Gọi hàm `a(n - 1)` trong vòng lặp 3 lần: $3 \times (f_{n-1} + 1)$
- Cộng trong vòng lặp: $3$ phép
- Trừ trong vòng lặp: $n$ phép
- Trả về `x`: 1 phép

Tổng:

$$
f_n = 1 + 1 + 3(f_{n-1} + 1) + 2n + 1 = 3f_{n-1} + 2n + 11
$$

---

#### d)

$$
f_n = \frac{-3^n + 2n + 13}{12}
$$


## Câu 4:
#### a. 1785


#### b Xác định đa thức và độ phức tạp

Số lần thực thi lệnh `print` được xác định bởi ba vòng lặp lồng nhau như sau:

- Vòng ngoài: $i$ chạy từ $1$ đến $n$
- Với mỗi $i$, $j$ chạy từ $1$ đến $i$
- Với mỗi $j$, $k$ chạy từ $1$ đến $i$

Vậy tổng số lần lệnh `print` được thực thi là:

$$
T(n) = \sum_{i=1}^{n} \sum_{j=1}^{i} \sum_{k=1}^{i} 1 = \sum_{i=1}^{n} i \cdot i = \sum_{i=1}^{n} i^2
$$

Sử dụng công thức tổng các bình phương:

$$
\sum_{i=1}^{n} i^2 = \frac{n(n+1)(2n+1)}{6}
$$

Vậy:

$$
T(n) = \frac{n(n+1)(2n+1)}{6}
$$

Đây là một đa thức bậc 3. Khai triển ra ta có:

$$
T(n) = \frac{2n^3 + 3n^2 + n}{6} = \frac{1}{3}n^3 + \frac{1}{2}n^2 + \frac{1}{6}n
$$

Vì vậy, chương trình có độ phức tạp:

$$
\mathcal{O}(n^3)
$$


In [1]:
import numpy as np

# Định nghĩa ma trận M ban đầu từ đề bài
M = np.array([
    [0, 0, 0, 0, 1],  # a
    [0, 1, 0, 0, 0],  # b
    [0, 0, 1, 1, 1],  # c
    [1, 0, 0, 1, 1],  # d
    [0, 0, 1, 0, 0]   # e
], dtype=int)

n = M.shape[0]
W = M.copy()

print("W0 (Ma trận ban đầu):")
print(W)

# Danh sách lưu các ma trận Wk nếu cần dùng lại
W_list = [W.copy()]

# Thuật toán Warshall
for k in range(n):
    for i in range(n):
        for j in range(n):
            W[i][j] = W[i][j] or (W[i][k] and W[k][j])
    print(f"\nW{k+1} (sau khi thêm đỉnh trung gian {k+1}):")
    print(W)
    W_list.append(W.copy())

# In bao đóng bắc cầu M*
print("\nMa trận bao đóng bắc cầu M*:")
print(W)

W0 (Ma trận ban đầu):
[[0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 1 1 1]
 [1 0 0 1 1]
 [0 0 1 0 0]]

W1 (sau khi thêm đỉnh trung gian 1):
[[0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 1 1 1]
 [1 0 0 1 1]
 [0 0 1 0 0]]

W2 (sau khi thêm đỉnh trung gian 2):
[[0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 1 1 1]
 [1 0 0 1 1]
 [0 0 1 0 0]]

W3 (sau khi thêm đỉnh trung gian 3):
[[0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 1 1 1]
 [1 0 0 1 1]
 [0 0 1 1 1]]

W4 (sau khi thêm đỉnh trung gian 4):
[[0 0 0 0 1]
 [0 1 0 0 0]
 [1 0 1 1 1]
 [1 0 0 1 1]
 [1 0 1 1 1]]

W5 (sau khi thêm đỉnh trung gian 5):
[[1 0 1 1 1]
 [0 1 0 0 0]
 [1 0 1 1 1]
 [1 0 1 1 1]
 [1 0 1 1 1]]

Ma trận bao đóng bắc cầu M*:
[[1 0 1 1 1]
 [0 1 0 0 0]
 [1 0 1 1 1]
 [1 0 1 1 1]
 [1 0 1 1 1]]
