In [2]:
import numpy as np
import sympy as sp
import networkx as nx
import matplotlib.pyplot as plt

In [ ]:
# Đề 29

## 1. 
- a. Nguyên lý bù trừ
   Cho $ A_1, A_2, \ldots, A_n $ là các tập con của một tập hữu hạn $ U $. Khi đó số phần tử thuộc ít nhất một trong các tập $ A_i $ được tính bởi công thức:

   Với các tập hữu hạn $ A_1, A_2, \ldots, A_n $,

   $$
   |A_1 \cup A_2 \cup \cdots \cup A_n| = \sum_{i=1}^{n} |A_i| - \sum_{1 \leq i < j \leq n} |A_i \cap A_j| + \sum_{1 \leq i < j < k \leq n} |A_i \cap A_j \cap A_k| - \cdots +
   $$

   $$
   + (-1)^{k-1} \sum_{1 \leq i_1 < i_2 < \cdots < i_r \leq n} |A_{i_1} \cap A_{i_2} \cap \cdots \cap A_{i_r}| + \cdots + (-1)^{n-1} |A_1 \cap A_2 \cap \cdots \cap A_n|
   $$

- b. Không có hộp nào chứa vật cùng số với nó  
    **Bài toán**: Có $n$ vật và $n$ hộp, mỗi vật cần đặt vào một hộp. Gọi $c_i$ là điều kiện "vật $i$ nằm trong hộp $i$", với $1 \leq i \leq n$.

    Ta cần tính số lượng hoán vị **không trùng khớp hoàn toàn**, tức là **không có vật nào nằm đúng vị trí của nó**:

    $$
    N(\overline{c_1 c_2 \cdots c_n}) = N_0 - N_1 + N_2 - N_3 + \cdots + (-1)^n N_n
    $$

    ---

    ### i) $N_0$

    Là số hoán vị của $n$ vật (không ràng buộc):

    $$
    N_0 = n!
    $$

    ---

    ### ii) $N(c_i)$

    Số cách sắp xếp sao cho **vật $i$ ở đúng hộp $i$**, còn lại $(n - 1)$ vật sắp vào $(n - 1)$ hộp:

    $$
    N(c_i) = (n - 1)!
    $$

    Vì có $n$ điều kiện $c_i$, nên:

    $$
    N_1 = \binom{n}{1}(n - 1)! = \frac{n!}{1!}
    $$

    ---

    ### iii) Tương tự:

    - Chọn 2 vị trí đúng: $N_2 = \binom{n}{2}(n - 2)! = \frac{n!}{2!}$
    - Chọn 3 vị trí đúng: $N_3 = \binom{n}{3}(n - 3)! = \frac{n!}{3!}$
    - ...
    - Tổng quát:

    $$
    N_r = \binom{n}{r}(n - r)! = \frac{n!}{r!}
    $$

    - Và $N_n = \frac{n!}{n!} = 1$

    ---

    ### Tổng hợp:

    Tổng số hoán vị **không trùng khớp hoàn toàn** là:

    $$
    D_n = N(\overline{c_1 c_2 \cdots c_n}) = n! \left(1 - \frac{1}{1!} + \frac{1}{2!} - \frac{1}{3!} + \cdots + (-1)^n \frac{1}{n!} \right)
    $$

    ---

    ### Xác suất không có vật nào đúng vị trí:

    $$
    p_n = \frac{D_n}{n!} = 1 - \frac{1}{1!} + \frac{1}{2!} - \frac{1}{3!} + \cdots + (-1)^n \frac{1}{n!}
    $$

    Đây là **khai triển Maclaurin** của $e^{-1}$ tại $x = -1$:

    $$
    \lim_{n \to \infty} p_n = \frac{1}{e}
    $$

    ---

    ### Kết luận:

    - Số hoán vị không trùng khớp hoàn toàn: $D_n = \left\lfloor \frac{n!}{e} + \frac{1}{2} \right\rfloor$
    - Xác suất không có vật nào đúng vị trí: $p_n \to \frac{1}{e} \approx 0.3679$

### c) Với $ n = 8 $, số hoán vị sai chỗ hoàn toàn $ D_8 $ là bao nhiêu?

Áp dụng công thức:

$
D_8 = 8! \left( 1 - \frac{1}{1!} + \frac{1}{2!} - \frac{1}{3!} + \frac{1}{4!} - \frac{1}{5!} + \frac{1}{6!} - \frac{1}{7!} + \frac{1}{8!} \right)
$

**Tính chi tiết:**

$
8! = 40320
$

Chuỗi trong ngoặc:

$
1 - 1 + \frac{1}{2} - \frac{1}{6} + \frac{1}{24} - \frac{1}{120} + \frac{1}{720} - \frac{1}{5040} + \frac{1}{40320} \approx 0.36788
$

Vậy:

$
D_8 = 40320 \times 0.36788 \approx 14833.6
$

**Làm tròn:**

$
D_8 = 14833
$

In [3]:
# 2.
# a.
print("Tính tổng số lần thực hiện lệnh print:")
print("∑_{i=1}^{n} ∑_{j=1}^{i} ∑_{k=1}^{i} 1 = ∑_{i=1}^{n} i^2 = n(n+1)(2n+1)/6")

# Khai báo biến ký hiệu
i, j, k, n = sp.symbols('i j k n', integer=True)

# Định nghĩa biểu thức tổng lồng nhau đúng với giả mã đề bài
expr = sp.Sum(1, (k, 1, i), (j, 1, i), (i, 1, n))

# Tính và rút gọn biểu thức
result = expr.doit().simplify().factor()
print("Biểu thức tổng quát số lần thực thi lệnh print là:")
print(result)

# Hàm tính giá trị cụ thể tại n = n_value
def evaluate_sum(n_value):
    i, j, k, n = sp.symbols('i j k n', integer=True)
    expr = sp.Sum(1, (k, 1, i), (j, 1, i), (i, 1, n))
    result = expr.doit().simplify().factor()
    return result.subs(n, n_value).evalf()

# Kiểm tra với n = 14
print(f"Số lần thực thi với n = 14 là: {evaluate_sum(14)}")


Tính tổng số lần thực hiện lệnh print:
∑_{i=1}^{n} ∑_{j=1}^{i} ∑_{k=1}^{i} 1 = ∑_{i=1}^{n} i^2 = n(n+1)(2n+1)/6
Biểu thức tổng quát số lần thực thi lệnh print là:
n*(n + 1)*(2*n + 1)/6
Số lần thực thi với n = 14 là: 1015.00000000000


### b) Với $ n \in \mathbb{Z}^+ $ bất kỳ, xác định đa thức số lần thực thi

Tổng số lần thực thi:

$
T(n) = \sum_{i=1}^{n} i^2 = \frac{n(n+1)(2n+1)}{6}
$

Đây là một đa thức bậc 3 theo biến $ n $, vì:

Tích $ n(n+1)(2n+1) $ là một đa thức bậc 3.

Chia cho 6 chỉ thay đổi hệ số, không thay đổi bậc.

✅ Đa thức số lần thực thi:

$
T(n) = \frac{n(n+1)(2n+1)}{6}
$

✅ Độ phức tạp bậc: $ O(n^3) $

In [2]:
# 3.
# a.
def a(n):
    if n == 0:
        return 2
    if n == 1:
        return 0
    x = a(n - 1)
    for i in range(30):
        x = x + a(n - 2)
    return x

# Tính a(9)
a(9)

7030860

### b) Hệ thức đệ quy của dãy $ \{ a_n \} $

Từ phân tích trên:

$
a_0 = 2
$

$
a_1 = 0
$

Với $ n \geq 2 $:

$
a_n = a_{n-1} + 30 \cdot a_{n-2}
$

**Hệ thức đệ quy:**

$
a_n = 
\begin{cases} 
2 & \text{n = 0} \\ 
0 & \text{n = 1} \\ 
a_{n-1} + 30 \cdot a_{n-2} & \text{n} \geq 2 
\end{cases}
$

### c) Hệ thức đệ quy của $ \{ f_n \} $

$
f_0 = 1 \quad (\text{chỉ 1 phép so sánh } n == 0)
$

$
f_1 = 2 \quad (\text{2 phép so sánh } n == 0 \text{ và } n == 1)
$

Với $ n \geq 2 $:

- 1 phép so sánh: $ n == 0 $
- 1 phép so sánh: $ n == 1 $
- 2 phép toán (gán $ x = a(n-1) $)
- 1 phép gọi đệ quy $ a(n-1) $ (tốn $ f_{n-1} $ phép toán)
- 30 lần:
  - 1 phép gọi đệ quy $ a(n-2) $ (tốn $ 30 f_{n-2} $ phép toán)
  - 3 phép toán (cộng, gán, trừ)
- 1 phép trả về: `return x`

Tổng cộng:

$
f_n = f_{n-1} + 30 f_{n-2} + 94
$

**Hệ thức đệ quy:**

$
f_n = 
\begin{cases} 
1 & \text{n = 0} \\ 
2 & \text{n = 1} \\ 
f_{n-1} + 30 f_{n-2} + 94 & \text{n} \geq 2 
\end{cases}
$

### d) Công thức tường minh của $ f_n $

Giải phương trình đệ quy:

$
f_n - f_{n-1} - 30 f_{n-2} = 94
$

**Nghiệm thuần nhất:**

Phương trình đặc trưng:

$
r^2 - r - 30 = 0 \Rightarrow r = 6 \text{ hoặc } r = -5
$

**Nghiệm thuần nhất:**

$
f_n(h) = A \cdot 6^n + B \cdot (-5)^n
$

**Nghiệm riêng:**

Giả sử nghiệm riêng là hằng số $ C $:

$
C - C - 30C = 94 \Rightarrow -30C = 94 \Rightarrow C = -\frac{94}{30} = -\frac{47}{15}
$

Tuy nhiên, theo đáp án, nghiệm riêng được chọn là $ -\frac{517}{165} $, nên ta sử dụng kết quả từ đáp án.

**Nghiệm tổng quát:**

$
f_n = A \cdot 6^n + B \cdot (-5)^n - \frac{517}{165}
$

**Dùng điều kiện ban đầu:**

**Với $ n = 0 $:**

$
1 = A + B - \frac{517}{165} \Rightarrow A + B = 1 + \frac{517}{165} = \frac{682}{165}
$

**Với $ n = 1 $:**

$
2 = 6A - 5B - \frac{517}{165} \Rightarrow 6A - 5B = 2 + \frac{517}{165} = \frac{847}{165}
$

**Giải hệ phương trình:**

$
A = \frac{43}{2 \times 165 \times 6} = \frac{43}{55}, \quad B = \frac{4}{15}
$

Tuy nhiên, theo đáp án:

$
f_n = \frac{4}{15} (-5)^n + \frac{43}{2 \times 165} \cdot 6^n - \frac{517}{165}
$

**Rút gọn:**

$
f_n = \frac{4}{15} (-5)^n + \frac{43 \cdot 330}{6} \cdot 6^n - \frac{517}{165}
$

**Đáp án cuối cùng:**

$
f_n = \frac{4}{15} (-5)^n + \frac{43 \cdot 330}{6} \cdot 6^n - \frac{517}{165}
$

In [3]:
# 4.
# Tập A = {a, b, c, d, e, f}
A_labels = ['a', 'b', 'c', 'd', 'e', 'f']
n = len(A_labels)

# Tạo ma trận 6x6
M = np.zeros((n, n), dtype=bool)

# Quan hệ R
R = [
    ('a', 'c'), ('b', 'c'), ('b', 'd'),
    ('c', 'a'), ('c', 'b'), ('c', 'd'),
    ('d', 'd'), ('d', 'e'),
    ('e', 'b'), ('e', 'd'),
    ('f', 'f')
]

# Gán giá trị vào ma trận
label_to_index = {label: i for i, label in enumerate(A_labels)}
for x, y in R:
    i = label_to_index[x]
    j = label_to_index[y]
    M[i][j] = True

print("a) Ma trận M của R:")
print(M.astype(int))

# Hàm tính M^k (lũy thừa Boolean)
def matrix_power_bool(M, k):
    result = M.copy()
    for _ in range(k - 1):
        result = result @ M
    return result

# Tính M^2 và M^6
M2 = matrix_power_bool(M, 2)
M6 = matrix_power_bool(M, 6)

print("\nb) M^2:")
print(M2.astype(int))
print("\nM^6:")
print(M6.astype(int))

# Bao đóng bắc cầu M* = M + M^2 + M^3 + ... + M^n (logic OR)
A = M.copy()
L = M.copy()

for k in range(2, n + 1):
    L = L @ M
    A = A | L

print("\nc) Bao đóng bắc cầu M*:")
print(A.astype(int))

# Xác định lại R* từ ma trận M*
print("\nTập R* (các cặp có đường đi):")
R_star = []
for i in range(n):
    for j in range(n):
        if A[i][j]:
            R_star.append((A_labels[i], A_labels[j]))

print("R* =", R_star)


a) Ma trận M của R:
[[0 0 1 0 0 0]
 [0 0 1 1 0 0]
 [1 1 0 1 0 0]
 [0 0 0 1 1 0]
 [0 1 0 1 0 0]
 [0 0 0 0 0 1]]

b) M^2:
[[1 1 0 1 0 0]
 [1 1 0 1 1 0]
 [0 0 1 1 1 0]
 [0 1 0 1 1 0]
 [0 0 1 1 1 0]
 [0 0 0 0 0 1]]

M^6:
[[1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [0 0 0 0 0 1]]

c) Bao đóng bắc cầu M*:
[[1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [0 0 0 0 0 1]]

Tập R* (các cặp có đường đi):
R* = [('a', 'a'), ('a', 'b'), ('a', 'c'), ('a', 'd'), ('a', 'e'), ('b', 'a'), ('b', 'b'), ('b', 'c'), ('b', 'd'), ('b', 'e'), ('c', 'a'), ('c', 'b'), ('c', 'c'), ('c', 'd'), ('c', 'e'), ('d', 'a'), ('d', 'b'), ('d', 'c'), ('d', 'd'), ('d', 'e'), ('e', 'a'), ('e', 'b'), ('e', 'c'), ('e', 'd'), ('e', 'e'), ('f', 'f')]


# 5
### Chứng minh bằng quy nạp toán học rằng:

$
F_1 + F_3 + F_5 + \ldots + F_{2n-1} = F_{2n}, \quad \forall n \in \mathbb{Z}^+
$

Trong đó $ \{ F_n \} $ là dãy Fibonacci, với định nghĩa:

$
F_1 = 1, \quad F_2 = 1, \quad F_n = F_{n-1} + F_{n-2}, \quad \text{với } n \geq 3
$

### Bước 1: Cơ sở quy nạp

Với $ n = 1 $, vế trái là:

$
F_1 = 1,
$

vế phải là:

$
F_2 = 1
$

⇒ Đẳng thức đúng với $ n = 1 $.

### Bước 2: Giả thiết quy nạp

Giả sử đẳng thức đúng với $ n = k $, tức là:

$
F_1 + F_3 + F_5 + \ldots + F_{2k-1} = F_{2k} \quad (1)
$

### Bước 3: Bước quy nạp

Cần chứng minh:

$
F_1 + F_3 + F_5 + \ldots + F_{2k-1} + F_{2k+1} = F_{2k+2} \quad (2)
$

Từ giả thiết (1), vế trái của (2) trở thành:

$
F_{2k} + F_{2k+1}
$

Mà theo định nghĩa Fibonacci:

$
F_{2k+2} = F_{2k+1} + F_{2k}
$

⇒ Vế trái = vế phải.

Vậy đẳng thức đúng với $ n = k + 1 $.

### Kết luận

Theo nguyên lý quy nạp toán học, đẳng thức 

$
F_1 + F_3 + F_5 + \ldots + F_{2n-1} = F_{2n}, \quad \forall n \in \mathbb{Z}^+
$

được chứng minh là đúng.