### Câu 1:
## Bước 1: Xét cơ sở n = 0 
(thay vào đề tính)
Vậy công thức đúng với n = 0

## Bước 2: Giả thuyết quy nạp

Giả sử với một số $ k \geq 0 $ bất kỳ, phương trình đúng, tức là:

$$
F_0 + F_2 + F_4 + \cdots + F_{2k} = F_{2k+1} - 1.
$$

---

## Bước 3: Chứng minh với $ n = k + 1 $

Ta cần chứng minh:

$$
F_0 + F_2 + F_4 + \cdots + F_{2k} + F_{2(k+1)} = F_{2(k+1)+1} - 1.
$$

Dùng giả thiết quy nạp:

$$
F_0 + F_2 + \cdots + F_{2k} + F_{2k+2} = (F_{2k+1} - 1) + F_{2k+2}.
$$

Vậy cần chứng minh:

$$
F_{2k+1} - 1 + F_{2k+2} = F_{2k+3} - 1.
$$

Ta xét vế trái:

$$
F_{2k+1} + F_{2k+2} - 1.
$$

Theo định nghĩa dãy Fibonacci:

$$
F_{2k+3} = F_{2k+2} + F_{2k+1}.
$$

Vậy:

$$
F_{2k+1} + F_{2k+2} - 1 = F_{2k+3} - 1,
$$

đúng với vế phải.

---

## Kết luận

Phương trình đúng với $ n = 0 $ (bước cơ sở), và nếu đúng với $ n = k $ thì đúng với $ n = k + 1 $ (bước quy nạp).

Do đó, theo nguyên lý quy nạp toán học, ta có:

$$
F_0 + F_2 + F_4 + \cdots + F_{2n} = F_{2n+1} - 1, \quad \forall n \in \mathbb{N}.
$$

### Câu 2:
## Câu a) Tính nhanh $a_9$

Xét đoạn mã Python:

```python
def a(n):
    if n == 0:
        return -3
    if n == 1:
        return 7
    x = a(n - 1)
    for i in range(2):
        x = x + a(n - 2)
    return x
a(6) = 81


### Câu 2BCD:
## Câu b) Hệ thức đệ quy của $ a_n $


Từ đoạn chương trình, ta có:

$$
a_n = a_{n-1} + 2 \cdot a_{n-2},
$$

với 

$$
a_0 = -3, \quad a_1 = 7.
$$

## c) Đặt $ f_n $ là số phép toán (so sánh, gán, số học) để tính $ a_n $

### Với $ n = 0 $ 
- Dòng 2: 1 phép so sánh


→ Tổng cộng:
$$
f_0 = 1 \quad \
$$

### Với $ n = 1 $:
- Dòng 2 và 4: 1 phép so sánh mỗi dòng
---
→ Tổng cộng:
$$
f_1 = 1+1=2 \quad \
$$

### Với $ n \geq 2 $:
Ta phân tích từng dòng:
- Dòng 2–5: 2 phép so sánh
- Dòng 6: 1 phép gán + 1 phép toán logic + 1 lời gọi hàm $ a(n-1) $ → cần $ f_{n-1} $ phép toán + 2 phép toán
- Dòng 7–8: Lặp 2 lần:
  - Mỗi lần:
    - 1 lời gọi $ a(n-2) $ → mỗi lần cần $ f_{n-2} $ phép toán
    - 2 phép toán số học và 1 phép gán

→ Tổng cộng:
$$
f_n = 1 + 1 + f_{n-1} + 2 + 2(f_{n-2} + 3) = f_{n-1} + 2f_{n-2} + 10
$$

### ✅ Hệ thức truy hồi:
$$
f_n = f_{n-1} + 2f_{n-2} + 10, \quad f_0 = f_1 = 1
$$

## Công thức cho $ f_n $

Công thức cho $ f_n $ được cho bởi:

$$
f_n = - \frac{8(-1)^n - 14 \cdot 2^n + 15}{3}
$$

### Câu 3: 
## Phân tích độ phức tạp của chương trình

### 1. Theo quy tắc nhân

Với mỗi $ i $ cố định, dòng 2–4 thực hiện $ n \times i = i^2 $ lệnh `print`. 

### 2. Theo quy tắc cộng

Chương trình thực hiện:

$$
\sum_{i=1}^{n} i^2 = \frac{n(n+1)(2n+1)}{6}
$$

Do đó, độ phức tạp của chương trình là:

$$
\in O(n^3) \text{ lệnh print.}
$$

### Kết luận

Chương trình có độ phức tạp bậc 3.

In [3]:
import sympy as sp
# Khai báo biến ký hiệu
i, j, k, n = sp.symbols('i j k n', integer=True)

# Định nghĩa biểu thức tổng lồng nhau đúng với giả mã đề bài
expr = sp.Sum(1, (k, 1, i), (j, 1, i), (i, 1, n))

# Tính và rút gọn biểu thức
result = expr.doit().simplify().factor()
print("Biểu thức tổng quát số lần thực thi lệnh print là:")
print(result)

# Hàm tính giá trị cụ thể tại n = n_value
def evaluate_sum(n_value):
    i, j, k, n = sp.symbols('i j k n', integer=True)
    expr = sp.Sum(1, (k, 1, i), (j, 1, i), (i, 1, n))
    result = expr.doit().simplify().factor()
    return result.subs(n, n_value).evalf()

# Kiểm tra với n = 6
print(f"Số lần thực thi với n = 6 là: {evaluate_sum(6)}")

Biểu thức tổng quát số lần thực thi lệnh print là:
n*(n + 1)*(2*n + 1)/6
Số lần thực thi với n = 6 là: 91.0000000000000


### Câu 4:
## 1. 
- a. Nguyên lý bù trừ
   Cho $ A_1, A_2, \ldots, A_n $ là các tập con của một tập hữu hạn $ U $. Khi đó số phần tử thuộc ít nhất một trong các tập $ A_i $ được tính bởi công thức:

   Với các tập hữu hạn $ A_1, A_2, \ldots, A_n $,

   $$
   |A_1 \cup A_2 \cup \cdots \cup A_n| = \sum_{i=1}^{n} |A_i| - \sum_{1 \leq i < j \leq n} |A_i \cap A_j| + \sum_{1 \leq i < j < k \leq n} |A_i \cap A_j \cap A_k| - \cdots +
   $$

   $$
   + (-1)^{k-1} \sum_{1 \leq i_1 < i_2 < \cdots < i_r \leq n} |A_{i_1} \cap A_{i_2} \cap \cdots \cap A_{i_r}| + \cdots + (-1)^{n-1} |A_1 \cap A_2 \cap \cdots \cap A_n|
   $$

- b. Không có hộp nào chứa vật cùng số với nó  
    **Bài toán**: Có $n$ vật và $n$ hộp, mỗi vật cần đặt vào một hộp. Gọi $c_i$ là điều kiện "vật $i$ nằm trong hộp $i$", với $1 \leq i \leq n$.

    Ta cần tính số lượng hoán vị **không trùng khớp hoàn toàn**, tức là **không có vật nào nằm đúng vị trí của nó**:

    $$
    N(\overline{c_1 c_2 \cdots c_n}) = N_0 - N_1 + N_2 - N_3 + \cdots + (-1)^n N_n
    $$

    ---

    ### i) $N_0$

    Là số hoán vị của $n$ vật (không ràng buộc):

    $$
    N_0 = n!
    $$

    ---

    ### ii) $N(c_i)$

    Số cách sắp xếp sao cho **vật $i$ ở đúng hộp $i$**, còn lại $(n - 1)$ vật sắp vào $(n - 1)$ hộp:

    $$
    N(c_i) = (n - 1)!
    $$

    Vì có $n$ điều kiện $c_i$, nên:

    $$
    N_1 = \binom{n}{1}(n - 1)! = \frac{n!}{1!}
    $$

    ---

    ### iii) Tương tự:

    - Chọn 2 vị trí đúng: $N_2 = \binom{n}{2}(n - 2)! = \frac{n!}{2!}$
    - Chọn 3 vị trí đúng: $N_3 = \binom{n}{3}(n - 3)! = \frac{n!}{3!}$
    - ...
    - Tổng quát:

    $$
    N_r = \binom{n}{r}(n - r)! = \frac{n!}{r!}
    $$

    - Và $N_n = \frac{n!}{n!} = 1$

    ---

    ### Tổng hợp:

    Tổng số hoán vị **không trùng khớp hoàn toàn** là:

    $$
    D_n = N(\overline{c_1 c_2 \cdots c_n}) = n! \left(1 - \frac{1}{1!} + \frac{1}{2!} - \frac{1}{3!} + \cdots + (-1)^n \frac{1}{n!} \right)
    $$

    ---

    ### Xác suất không có vật nào đúng vị trí:

    $$
    p_n = \frac{D_n}{n!} = 1 - \frac{1}{1!} + \frac{1}{2!} - \frac{1}{3!} + \cdots + (-1)^n \frac{1}{n!}
    $$

    Đây là **khai triển Maclaurin** của $e^{-1}$ tại $x = -1$:

    $$
    \lim_{n \to \infty} p_n = \frac{1}{e}
    $$

    ---

    ### Kết luận:

    - Số hoán vị không trùng khớp hoàn toàn: $D_n = \left\lfloor \frac{n!}{e} + \frac{1}{2} \right\rfloor$
    - Xác suất không có vật nào đúng vị trí: $p_n \to \frac{1}{e} \approx 0.3679$

### c) Với $ n = 8 $, số hoán vị sai chỗ hoàn toàn $ D_8 $ là bao nhiêu?

Áp dụng công thức:

$
D_8 = 8! \left( 1 - \frac{1}{1!} + \frac{1}{2!} - \frac{1}{3!} + \frac{1}{4!} - \frac{1}{5!} + \frac{1}{6!} - \frac{1}{7!} + \frac{1}{8!} \right)
$

**Tính chi tiết:**

$
8! = 40320
$

Chuỗi trong ngoặc:

$
1 - 1 + \frac{1}{2} - \frac{1}{6} + \frac{1}{24} - \frac{1}{120} + \frac{1}{720} - \frac{1}{5040} + \frac{1}{40320} \approx 0.36788
$

Vậy:

$
D_8 = 40320 \times 0.36788 \approx 14833.6
$

**Làm tròn:**

$
D_8 = 14833
$

In [5]:
#Câu 5: Bao đóng bắc cầu
import numpy as np
# Ma trận quan hệ ban đầu (kiểu boolean)
M = np.array([
    [0, 0, 1, 0, 0],
    [1, 1, 1, 0, 0],
    [1, 1, 0, 0, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 1, 0, 1]
], dtype=bool)

n = len(M)

# Khởi tạo A là M, để lưu tổng M + M^2 + ... + M^k
A = M.copy()

# Biến tạm L để nhân lũy thừa
L = M.copy()

# Tính các lũy thừa từ M^2 đến M^n và cộng dồn vào A
for k in range(2, n + 1):
    L = M.dot(L)        # M^k = M * M^{k-1}
    A += L              # Cộng dồn vào A: A = M + M^2 + ... + M^k
    print(f"M^{k}:\n", np.array(L, dtype=int))  # In ra M^k dưới dạng int
print("M* = M1 v M2 .. V Mn")
# In bao đóng bắc cầu (dưới dạng 0/1)
print("Transitive Closure (M*):\n", np.array(A, dtype=int))


M^2:
 [[1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [0 0 0 1 0]
 [1 1 1 0 1]]
M^3:
 [[1 1 1 0 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [0 0 0 1 0]
 [1 1 1 0 1]]
M^4:
 [[1 1 1 0 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [0 0 0 1 0]
 [1 1 1 0 1]]
M^5:
 [[1 1 1 0 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [0 0 0 1 0]
 [1 1 1 0 1]]
M* = M1 v M2 .. V Mn
Transitive Closure (M*):
 [[1 1 1 0 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [0 0 0 1 0]
 [1 1 1 0 1]]
