## Câu a) Tính nhanh $a_9$

Xét đoạn mã Python:

```python
def a(n):
    if n == 0:
        return -8
    if n == 1:
        return 8
    x = a(n - 1)
    for i in range(56):
        x = x + a(n - 2)
    return x
a(9) = -235799416


## Câu b) Hệ thức đệ quy của $ a_n $


Từ đoạn chương trình, ta có:

$$
a_n = a_{n-1} + 56 \cdot a_{n-2},
$$

với 

$$
a_0 = -8, \quad a_1 = 8.
$$

## c) Đặt $ f_n $ là số phép toán (so sánh, gán, số học) để tính $ a_n $

### Với $ n = 0 $ 
- Dòng 2: 1 phép so sánh


→ Tổng cộng:
$$
f_0 = 1 \quad \
$$

### Với $ n = 1 $:
- Dòng 2 và 4: 1 phép so sánh mỗi dòng
---
→ Tổng cộng:
$$
f_1 = 1+1=2 \quad \
$$

### Với $ n \geq 2 $:
Ta phân tích từng dòng:
- Dòng 2–5: 2 phép so sánh
- Dòng 6: 1 phép gán + 1 phép toán logic + 1 lời gọi hàm $ a(n-1) $ → cần $ f_{n-1} $ phép toán + 2 phép toán
- Dòng 7–8: Lặp 56 lần:
  - Mỗi lần:
    - 1 lời gọi $ a(n-2) $ → mỗi lần cần $ f_{n-2} $ phép toán
    - 2 phép toán số học và 1 phép gán

→ Tổng cộng:
$$
f_n = 1 + 1 + f_{n-1} + 2 + 56(f_{n-2} + 3) = f_{n-1} + 56f_{n-2} + 172
$$

### ✅ Hệ thức truy hồi:
$$
f_n = f_{n-1} + 56f_{n-2} + 172, \quad f_0 = f_1 = 1
$$

## d) Công thức tổng quát

Công thức cho $ f_n $ được cho bởi:

$$
f_n = (-707(-7)^n + 328 \cdot 8^n + 645)/210
$$



## Phân tích độ phức tạp của chương trình

### 1. Theo quy tắc nhân

Với mỗi $ i $ cố định, dòng 2–4 thực hiện $ n \times i = i^2 $ lệnh `print`. 

### 2. Theo quy tắc cộng

Chương trình thực hiện:

$$
\sum_{i=1}^{n} i^2 = \frac{n(n+1)(2n+1)}{6}
$$

Do đó, độ phức tạp của chương trình là:

$$
\in O(n^3) \text{ lệnh print.}
$$

### Kết luận

Chương trình có độ phức tạp bậc 3.

In [ ]:
#Câu 2:
print("∑_{i=1}^{n} ∑_{j=1}^{i} ∑_{k=1}^{i} 1 = ∑_{i=1}^{n} i^2 = n(n+1)(2n+1)/6")

# Khai báo biến ký hiệu
i, j, k, n = sp.symbols('i j k n', integer=True)

# Định nghĩa biểu thức tổng lồng nhau đúng với giả mã đề bài
expr = sp.Sum(1, (k, 1, i), (j, 1, i), (i, 1, n))

# Tính và rút gọn biểu thức
result = expr.doit().simplify().factor()
print("Biểu thức tổng quát số lần thực thi lệnh print là:")
print(result)

# Hàm tính giá trị cụ thể tại n = n_value
def evaluate_sum(n_value):
    i, j, k, n = sp.symbols('i j k n', integer=True)
    expr = sp.Sum(1, (k, 1, i), (j, 1, i), (i, 1, n))
    result = expr.doit().simplify().factor()
    return result.subs(n, n_value).evalf()

# Kiểm tra với n = 14
print(f"Số lần thực thi với n = 14 là: {evaluate_sum(14)}")

∑_{i=1}^{n} ∑_{j=1}^{i} ∑_{k=1}^{i} 1 = ∑_{i=1}^{n} i^2 = n(n+1)(2n+1)/6
Biểu thức tổng quát số lần thực thi lệnh print là:
n*(n + 1)*(2*n + 1)/6
Số lần thực thi với n = 14 là: 1015.00000000000


## 1.3. Hàm Euler phi

- i. Phát biểu, chứng minh công thức hàm Euler $ \varphi $  
    ### Hàm Euler: Công thức và chứng minh bằng bao hàm - loại trừ

    Cho số nguyên dương $n \geq 2$.

    Theo **định lý cơ bản của số học**, $n$ có phân tích:

    $$
    n = p_1^{e_1} p_2^{e_2} \cdots p_k^{e_k}
    $$

    trong đó $p_i$ là các số nguyên tố khác nhau, $e_i \in \mathbb{Z}^+$, với $1 \leq i \leq k$.

    ---

    Khi đó, **hàm Euler** (số lượng số nguyên dương $\leq n$ nguyên tố cùng nhau với $n$) là:

    $$
    \Phi(n) = n \prod_{i=1}^k \left(1 - \frac{1}{p_i} \right)
    $$

    ---

    ### Chứng minh bằng nguyên lý bao hàm - loại trừ (Inclusion-Exclusion)

    Một số nguyên dương $m$ là nguyên tố cùng nhau với $n$ **nếu không chia hết cho bất kỳ** $p_i$ nào ($1 \leq i \leq k$).

    Gọi $c_i$: điều kiện "$p_i$ là ước của $m$".

    Ta cần tính số lượng $m$ (trong $1 \leq m \leq n$) **không thỏa mãn bất kỳ $c_i$ nào**:

    $$
    N(\overline{c_1 c_2 \cdots c_k}) = N_0 - N_1 + N_2 - N_3 + \cdots + (-1)^k N_k
    $$

    ---

    #### i) $N_0 = n$

    Số lượng số nguyên từ 1 đến $n$.

    ---

    #### ii) $N_1 = \sum_{1 \leq i \leq k} N(c_i) = \sum_{i=1}^k \left\lfloor \frac{n}{p_i} \right\rfloor \approx \sum_{i=1}^k \frac{n}{p_i}$

    ---

    #### iii) $N_2$: số lượng $m$ chia hết đồng thời hai trong các $p_i$

    Vì $p_i, p_j$ nguyên tố khác nhau nên $\text{lcm}(p_i, p_j) = p_i p_j$, do đó:

    $$
    N_2 = \sum_{1 \leq i < j \leq k} \left\lfloor \frac{n}{p_i p_j} \right\rfloor \approx \sum_{1 \leq i < j \leq k} \frac{n}{p_i p_j}
    $$

    ---

    #### iv) Tương tự:

    - $N_3 = \sum_{1 \leq i < j < l \leq k} \frac{n}{p_i p_j p_l}$
    - ...
    - $N_r = \sum_{1 \leq i_1 < i_2 < \cdots < i_r \leq k} \frac{n}{p_{i_1} p_{i_2} \cdots p_{i_r}}$
    - ...
    - $N_k = \frac{n}{p_1 p_2 \cdots p_k}$

    ---

    Vì mỗi số hạng đều có thừa số chung là $n$, nên:

    $$
    \Phi(n) = n \left[ 1 - \sum_{i=1}^k \frac{1}{p_i}
    + \sum_{1 \leq i < j \leq k} \frac{1}{p_i p_j}
    - \sum_{1 \leq i < j < l \leq k} \frac{1}{p_i p_j p_l}
    + \cdots + (-1)^k \frac{1}{p_1 p_2 \cdots p_k}
    \right]
    $$

    ---

    Nhận thấy biểu thức trong ngoặc là:

    $$
    \prod_{i=1}^k \left(1 - \frac{1}{p_i} \right)
    $$

    ---

    ### Kết luận:

    $$
    \Phi(n) = n \prod_{i=1}^k \left(1 - \frac{1}{p_i} \right)
    $$

    ---

    ✅ **Ý nghĩa**: Hàm Euler đếm số lượng số nguyên từ 1 đến $n$ nguyên tố cùng nhau với $n$ — được tính gọn qua tích liên quan đến phân tích nguyên tố của $n$.



- ii. Tính $ \varphi(2025) $
    ---

    ## Bước 1: Phân tích thừa số nguyên tố của $ 2025 $

Ta phân tích $ 2025 $:

$$
2025 = 45^2
$$

Với 

$$
45 = 9 \times 5 = 3^2 \times 5
$$

Do đó:

$$
2025 = 45^2 = (3^2 \times 5)^2 = 3^4 \times 5^2
$$

---

## Bước 2: Công thức tính hàm phi Euler cho số nguyên tố

Với 

$$
n = p_1^{\alpha_1} \times p_2^{\alpha_2} \times \cdots \times p_k^{\alpha_k},
$$

có công thức:

$$
\phi(n) = n \times \prod_{i=1}^{k} \left(1 - \frac{1}{p_i}\right)
$$

---

## Bước 3: Tính $ \phi(2025) $

Ở đây:

- $ p_1 = 3, \quad \alpha_1 = 4 $
- $ p_2 = 5, \quad \alpha_2 = 2 $

Do đó:

$$
\phi(2025) = 2025 \times \left(1 - \frac{1}{3}\right) \times \left(1 - \frac{1}{5}\right)
$$

Tính từng phần:

$$
1 - \frac{1}{3} = \frac{2}{3}, \quad 1 - \frac{1}{5} = \frac{4}{5}
$$

Vậy:

$$
\phi(2025) = 2025 \times \frac{2}{3} \times \frac{4}{5} = 2025 \times \frac{8}{15}
$$

---

## Bước 4: Tính giá trị cuối cùng

$$
2025 \times \frac{8}{15} = \left(2025 \div 15\right) \times 8 = 135 \times 8 = 1080
$$

---

## Kết luận:

$$
\phi(2025) = 1080
$$


## Bước 1: Xét cơ sở n = 0 
(thay vào đề tính)
Vậy công thức đúng với n = 0

## Bước 2: Giả thuyết quy nạp

Giả sử với một số $ k \geq 0 $ bất kỳ, phương trình đúng, tức là:

$$
F_0 + F_2 + F_4 + \cdots + F_{2k} = F_{2k+1} - 1.
$$

---

## Bước 3: Chứng minh với $ n = k + 1 $

Ta cần chứng minh:

$$
F_0 + F_2 + F_4 + \cdots + F_{2k} + F_{2(k+1)} = F_{2(k+1)+1} - 1.
$$

Dùng giả thiết quy nạp:

$$
F_0 + F_2 + \cdots + F_{2k} + F_{2k+2} = (F_{2k+1} - 1) + F_{2k+2}.
$$

Vậy cần chứng minh:

$$
F_{2k+1} - 1 + F_{2k+2} = F_{2k+3} - 1.
$$

Ta xét vế trái:

$$
F_{2k+1} + F_{2k+2} - 1.
$$

Theo định nghĩa dãy Fibonacci:

$$
F_{2k+3} = F_{2k+2} + F_{2k+1}.
$$

Vậy:

$$
F_{2k+1} + F_{2k+2} - 1 = F_{2k+3} - 1,
$$

đúng với vế phải.

---

## Kết luận

Phương trình đúng với $ n = 0 $ (bước cơ sở), và nếu đúng với $ n = k $ thì đúng với $ n = k + 1 $ (bước quy nạp).

Do đó, theo nguyên lý quy nạp toán học, ta có:

$$
F_0 + F_2 + F_4 + \cdots + F_{2n} = F_{2n+1} - 1, \quad \forall n \in \mathbb{N}.
$$

In [5]:
#Câu 5: Bao đóng bắc cầu
import numpy as np
# Ma trận quan hệ ban đầu (kiểu boolean)
M = np.array([
    [1, 0, 0, 1, 0, 0],
    [1, 0, 0, 0, 1, 0],
    [0, 1, 1, 0, 1, 0],
    [1, 1, 1, 0, 0, 0],
    [1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1]
], dtype=bool)

n = len(M)

# Khởi tạo A là M, để lưu tổng M + M^2 + ... + M^k
A = M.copy()

# Biến tạm L để nhân lũy thừa
L = M.copy()

# Tính các lũy thừa từ M^2 đến M^n và cộng dồn vào A
for k in range(2, n + 1):
    L = M.dot(L)        # M^k = M * M^{k-1}
    A += L              # Cộng dồn vào A: A = M + M^2 + ... + M^k
    print(f"M^{k}:\n", np.array(L, dtype=int))  # In ra M^k dưới dạng int
print("M* = M1 v M2 .. V Mn")
# In bao đóng bắc cầu (dưới dạng 0/1)
print("Transitive Closure (M*):\n", np.array(A, dtype=int))


M^2:
 [[1 1 1 1 0 0]
 [1 0 0 1 0 0]
 [1 1 1 0 1 0]
 [1 1 1 1 1 0]
 [1 0 0 1 0 0]
 [0 0 0 0 0 1]]
M^3:
 [[1 1 1 1 1 0]
 [1 1 1 1 0 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 0 0]
 [0 0 0 0 0 1]]
M^4:
 [[1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [0 0 0 0 0 1]]
M^5:
 [[1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [0 0 0 0 0 1]]
M^6:
 [[1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [0 0 0 0 0 1]]
M* = M1 v M2 .. V Mn
Transitive Closure (M*):
 [[1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 0]
 [0 0 0 0 0 1]]
