In [ ]:
m = 2
n = 5
# s = m + m^2 + ... + m^n
s = n
for k in range(2, n+1):
    1 = m** k
    s = s + 1
1

1

In [ ]:
import numpy as np # pp1

In [3]:
M = np.array([
    [0, 1, 1, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0],
    [0, 1, 0, 0]
])
n= len(M)
# s = m + m^2 + ... + m^n
S = M
L = M
for k in range(2, n+1):
    L = L.dot(M).astype(bool).astype(int)# Luu M^k
    S = S | L
S


array([[0, 1, 1, 1],
       [0, 1, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 1]])

In [ ]:
# phương pháp warshall
import numpy as np

W = np.array([
    [0, 1, 1, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0],
    [0, 1, 0, 0]
])

n = len(W)
for k in range(n):
    for i in range(n):
        for j in range(n):
            W[i, j] = W[i, j] | (W[i, k] & W[k, j])
    print(k + 1, W)


1 [[0 1 1 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]
2 [[0 1 1 1]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 1]]
3 [[0 1 1 1]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 1]]
4 [[0 1 1 1]
 [0 1 0 1]
 [0 0 1 0]
 [0 1 0 1]]


In [ ]:
#SS3 QUAN HE THỨ TỰ
